### ISSUE TITLE
panic happens when trackuser

### ISSUE THREAD

**Issue by luxcgo** [Davincible/gotiktoklive#4]
Hi ,there! You're doing a great job, and I'm using your lib to grab stream url, but panic happens when `trackuser` according to the user feedback.

logs: https://github.com/go-olive/olive/issues/12#issuecomment-1147966803
code: https://github.com/go-olive/tv/blob/0870483c28b9581863877be8acd9f86a088252ab/tiktok.go#L36

**Comment by Davincible** [comment]
Thanks!
Do you have a bit more details about the panic that occurs?

**Comment by Davincible** [comment]
Thank you :)

The bugs should be fixed. I also noticed you only fetch the info from the room, so I added a `GetRoomInfo` method, this will only fetch the `Live.Info` data, and not start any go routines/connect to any websockets. You can use this to just fetch the info without tracking the stream.
